---
- hosts: testserver
  become: true

  tasks:
    - name: cleanup old image
      shell: docker stop rmit-store-test && docker rm rmit-store-test && docker rmi -f vvd0502/rmit-store-test
      ignore_errors: true
      
    - name: pull and build run docker container on webapp server
      community.docker.docker_container:
        name: rmit-store-test
        image: vvd0502/rmit-store-test
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "8081:80" 

- hosts: dbserver
  become: true

  tasks:
    - name: cleanup old image
      shell: docker stop rmit-store-test-db && docker rm rmit-store-test-db && docker rmi -f vvd0502/rmit-store-test-db
      ignore_errors: true


    - name: pull and build run docker container on test db server
      community.docker.docker_container:
        name: rmit-store-test-db
        image: vvd0502/rmit-store-test-db
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "8081:3306" 
